#!/usr/bin/env ruby
require 'termclock'
$-v = nil
STDOUT.sync = true

def version(logo_colour)
	emoji = ?🕐.ord.-(1).chr('utf-8')
	Time.now.strftime('%I').to_i.times { emoji.next! }

	_v = "#{emoji} This is Termclock v#{Termclock::VERSION}"
	vl_2 = _v.length / 2

	_v[0...vl_2].gradient(logo_colour[0], logo_colour[1], underline: true, bold: true) <<
		_v[vl_2..-1].gradient(logo_colour[1], logo_colour[2], underline: true, bold: true)
end

unless STDOUT.tty?
	IO.undef_method(:winsize)
	IO.define_method(:winsize) { [100, 100] }
end

LOGO_COLOUR = %w(ff0  f55 55f).map(&Termclock.method(:hex2rgb))

if ARGV.any? { |x| x[/\A\-(\-help|h)\z/] }
	puts <<~EOF
		TermClock: A clock that runs on the LinuxTerminal!

		\e[1;4mArguments:\e[0m

		\e[1m1. Help and Version:\e[0m
			--help|-h\t\t\tShows this help section
			--version|-v\t\t\tShows termclock version

		\e[1m2. Style:\e[0m
			--bold|-b\t\t\tMake texts bold
			--italic|-i\t\t\tMake texts italic
			--character=|char=\t\tDraws specified character
			--clean\t\t\t\tJust run the clean bare clock
			--colour=|-c=\t\t\tSpecify hex colour (4 colours)
			--text-colour=|-tc=\t\tSpecify text colour (2 colours)

			\u2B22 \e[3mColours has to be hex, 3 or 6 characters with or
			without the leading # in front\e[0m

		\e[1m3. Information:\e[0m
			--no-date|-nd\t\t\tShows no date
			--no-message|-nm\t\tShows no messages
			--no-sysinfo|-ni\t\tShows no system info
			--refresh=|r=\t\t\tSpecify delay or refresh time
			--no-logo|-nl\t\t\tDon't show the logo at the bottom

		\e[1m4. Antiflicker:\e[0m
			--antiflicker|-af\t\tDon't flicker terminal

			\u2B22 \e[3mIf refresh time is low or terminal is slow, use this option\e[0m

		\e[1m5. Formats:\e[0m
			--date-format=|-df=\t\tSpecify the date format
			--time-format=|-tf=\t\tSpecify the time format

			Usually the format looks like this:
			%H:%M:%S:%2N or %d %B, %Y

			\u2B22 \e[3mRun `date --help` to know more formats\e[0m

		Supported characters are 0 - 9, a - z, /, \\, !, %, and |.

		#{version(LOGO_COLOUR)}
	EOF

	exit 0
end

if ARGV.any? { |x| x[/\A\-(-version|v)\z/] }
	puts version(LOGO_COLOUR)
	exit 0
end

begin
	print "\e[?25l"

	arg_col = ARGV.find { |x| x[/\A\-(\-colour|\-color|c|)=.*\z/] } &.split(?=) &.at(1) &.split(?,)

	colours = if arg_col
		abort("4 colours are needed. Example: -c=f55,55f,55f,3eb") if arg_col.length != 4
		arg_col
	else
		%w(ff5555 5555ff 5555ff 33eebb)
	end

	colours.map! { |x|
		begin
			Termclock.hex2rgb(x)
		rescue ArgumentError
			abort $!.to_s
		end
	}

	chars = ARGV.find { |x| x[/\A\-(\-character|char)=.*\z/] } &.split(?=) &.at(1)
	Termclock::ParseCharacters.transform_characters!(*chars) if chars

	_refresh_time = ARGV.find { |x| x[/\A\-(\-refresh|r)=.*\z/] } &.split(?=) &.at(1)
	refresh_time = _refresh_time ? _refresh_time.to_f : 0.1

	_time_format = ARGV.find { |x| x[/\A\-(\-time\-format|tf)=.*\z/] } &.split(?=) &.at(1)
	time_format = _time_format ? _time_format : "%H %M %S %2N"

	_date_format = ARGV.find { |x| x[/\A\-(\-date\-format|df)=.*\z/] } &.split(?=) &.at(1)
	date_format = _date_format ? _date_format : "%a, %d %B %Y"

	text_colours = ARGV.find { |x| x[/\A\-(\-text\-colour|tc)=.*\z/] } &.split(?=) &.at(1) &.split(?,)
	abort("Text colours need 2 colours. Example: -tc=55f,3ce3b5") if text_colours && text_colours.length != 2

	bold = ARGV.any? { |x| x[/\A\-(\-bold|b)\z/] }
	italic = ARGV.any? { |x| x[/\A\-(\-italic|i)\z/] }
	anti_flicker = ARGV.any? { |x| x[/\A\-(\-antiflicker|af)\z/] }

	no_print_info = ARGV.any? { |x| x[/\A\-(\-no\-sysinfo|ni)\z/] }
	no_logo = ARGV.any? { |x| x[/\A\-(\-no\-logo|nl)\z/] }
	no_print_message = ARGV.any? { |x| x[/\A\-(\-no\-message|nm)\z/] }
	no_print_date = ARGV.any? { |x| x[/\A\-(\-no\-date|nd)\z/] }

	clean = ARGV.any? { |x| x[/\A\-(\-clean)\z/] }

	if clean
		no_print_info = no_print_message = no_print_date = no_logo = true
	end

	begin
		Time.now.strftime(time_format)
		Time.now.strftime(date_format)
	rescue
		abort "Date / Time format is invalid\n#{$!.to_s}"
	end

	Termclock.start(
		*colours,
		*text_colours,
		refresh: refresh_time,
		bold: bold,
		italic: italic,
		print_info: !no_print_info,
		print_message: !no_print_message,
		print_date: !no_print_date,
		no_logo: no_logo,
		time_format: time_format,
		date_format: date_format,
		logo_colour: LOGO_COLOUR,
		anti_flicker: anti_flicker
	)
rescue Interrupt, SignalException
	print "\e[H\e[2J\e[3J"
# rescue Errno::ENOTTY
	# abort "This should be run on a TTY! Also please don't pipe or redirect the output!"
ensure
	print "\e[?25h"
end
